version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test-env-size:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: true | xargs --show-limits

workflows:
  tests-env:
    jobs:
      - test-env-size